# Generated by Django 3.1.7 on 2021-03-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210321_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cat',
            field=models.ManyToManyField(to='blog.category', verbose_name='دسته بندی'),
        ),
    ]
