# Generated by Django 3.1.7 on 2021-03-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210322_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='status',
            field=models.CharField(choices=[('d', 'عدم نمایش'), ('p', 'نمایش')], default='p', max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='postcat', to='blog.Category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='weblog_setting',
            name='status',
            field=models.CharField(choices=[('d', 'عدم نمایش'), ('p', 'نمایش')], default='1', max_length=1, verbose_name='وضعیت'),
        ),
    ]
