# Generated by Django 3.1.7 on 2021-03-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210321_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblog_setting',
            name='status',
            field=models.CharField(choices=[('0', 'عدم نمایش'), ('1', 'نمایش')], default='1', max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='postcat', to='blog.Category', verbose_name='دسته بندی'),
        ),
    ]
